### PR TITLE
Creating login and logout

### PR DESCRIPTION
**Pull request by LinaGallardo**
In this branch use the gem "Devise" to create login and the logout.
creating_login_logout

### CODE REVIEW

**Comment by Jucerweb** [comment]
Could you show how looks the view "Create users" now ?

**Comment by LinaGallardo** [comment]
captura de pantalla 2018-12-20 a la s 11 31 08 a m

**Comment by Jucerweb** [comment]
Please delete the `log in` link from the bottom, there are two of them

**Comment by LinaGallardo** [comment]
> Please delete the `log in` link from the bottom, there are two of them
Done

**Review by Jucerweb — APPROVED** [review]

**Review by Jucerweb — APPROVED** [review]

**Pull request merged**
